add new tabs and restaurant component
bisonEdu/bootcamp pull request #2
Opened 2023-09-26 20:08 UTC by bisonEdu

add new page and restaurant component

2023-09-28 14:59 UTC, SArchieEdu requested changes

2023-09-28 14:59 UTC, SArchieEdu commented on src/pages/Main/components.jsx
> +  const [activeRestaurant, setActiveRestaurant] = useState(restaurants[0]);
эти состояния дублируют друг друга. нам не нужно хрнаить то, что мы можем легко получить. Тут достаточно хранить индекс

2023-09-28 14:59 UTC, SArchieEdu commented on src/components/Dish/component.jsx
> +  const min = 0;
такие константы лучше вынести за компонет и не создавать на каждом рендере

2023-10-01 10:54 UTC, bisonEdu commented on src/components/Dish/component.jsx
> +  const min = 0;
оке

2023-10-01 10:54 UTC, bisonEdu commented on src/pages/Main/components.jsx
> +  const [activeRestaurant, setActiveRestaurant] = useState(restaurants[0]);
понял, поправлю

2023-10-02 13:17 UTC, SArchieEdu approved these changes

2023-10-02 17:33 UTC, merged